"use client";
import moment from "moment";
import styles from "./analyticsReport.module.scss";

const ReportFooter = ({ reportType = "analytics" }) => {
  return (
    <div className={styles.footer}>
      <p>This is an automated {reportType} report generated by DragBizz.</p>
      <p>Report Generated on {moment().format("DD/MM/YYYY HH:mm:ss")}</p>
    </div>
  );
};

export default ReportFooter;
