// Feature keys aligned with dragbizz-retailer subscription modules
export const FEATURES = {
  STORE: "store",
  PRODUCT: "product",
  INVENTORY: "inventory",
  INVOICE: "invoice",
  CUSTOMER: "customer",
  SUPPLIER: "supplier",
  EXPENSE: "expense",
  CASHBOOK: "cashbook",
  PURCHASE_ORDER: "purchase_order",
  BILLING: "billing",
  REPORTS: "reports",
  PAYMENT_REMINDER: "payment_reminder",
  STAFF: "staff",
  SALES_ORDER: "sales_order",
  AI: "ai",
  ONLINE_STORE: "online_store",
};

export const FEATURE_DISPLAY_NAMES = {
  store: "Store Management",
  product: "Product Management",
  inventory: "Inventory Management",
  invoice: "Invoice Management",
  customer: "Customer Management",
  supplier: "Supplier Management",
  expense: "Expense Management",
  cashbook: "Cashbook",
  purchase_order: "Purchase Management",
  billing: "Bill Management",
  reports: "Reports & Analytics",
  payment_reminder: "Payment Reminders",
  staff: "Staff Management",
  sales_order: "Sales Orders",
  ai: "AI Suite",
  online_store: "Online Store",
};
