export const SIGNATURE_FONTS = [
    // Classic / Formal
    { id: "font-1", name: "Classic Script", family: "'Dancing Script', cursive" },
    { id: "font-3", name: "Modern Elegant", family: "'Satisfy', cursive" },
    { id: "font-4", name: "Artistic", family: "'Great Vibes', cursive" },
    { id: "font-8", name: "Formal Script", family: "'Parisienne', cursive" },
    { id: "font-14", name: "Royal Touch", family: "'Pinyon Script', cursive" },
    { id: "font-15", name: "French Style", family: "'Monsieur La Doulaise', cursive" },
    { id: "font-16", name: "Calligraphic", family: "'Herr Von Muellerhoff', cursive" },
    { id: "font-17", name: "Finest Line", family: "'Tangerine', cursive" },
    { id: "font-18", name: "Historic", family: "'Mrs Saint Delafield', cursive" },
    { id: "font-19", name: "Old World", family: "'Mr De Haviland', cursive" },
    { id: "font-20", name: "Venetian", family: "'Italianno', cursive" },
    { id: "font-23", name: "Elegant Flow", family: "'Qwigley', cursive" },
    { id: "font-38", name: "Petit Formal", family: "'Petit Formal Script', cursive" },
    { id: "font-39", name: "Rouge", family: "'Rouge Script', cursive" },
    { id: "font-40", name: "Aguafina", family: "'Aguafina Script', cursive" },
    { id: "font-45", name: "Quintessential", family: "'Quintessential', cursive" },
    { id: "font-50", name: "Norican", family: "'Norican', cursive" },
    { id: "font-51", name: "Arizonia", family: "'Arizonia', cursive" },
    { id: "font-61", name: "Miss Fajardose", family: "'Miss Fajardose', cursive" },
    { id: "font-68", name: "Ruthie", family: "'Ruthie', cursive" },

    // Casual / Handwritten
    { id: "font-2", name: "Bold Brush", family: "'Pacifico', cursive" },
    { id: "font-5", name: "Stylish Hand", family: "'Allura', cursive" },
    { id: "font-6", name: "Signature Flow", family: "'Alex Brush', cursive" },
    { id: "font-7", name: "Vintage Pen", family: "'Sacramento', cursive" },
    { id: "font-9", name: "Marker Style", family: "'Cookie', cursive" },
    { id: "font-10", name: "Retro Vibe", family: "'Yellowtail', cursive" },
    { id: "font-11", name: "Chic", family: "'Rochester', cursive" },
    { id: "font-12", name: "Hotel Sign", family: "'Grand Hotel', cursive" },
    { id: "font-28", name: "Handwritten", family: "'Homemade Apple', cursive" },
    { id: "font-29", name: "Notes", family: "'Cedarville Cursive', cursive" },
    { id: "font-30", name: "Quick Note", family: "'Nothing You Could Do', cursive" },
    { id: "font-31", name: "Playful", family: "'Gloria Hallelujah', cursive" },
    { id: "font-32", name: "Tall & Thin", family: "'Covered By Your Grace', cursive" },
    { id: "font-33", name: "Inked", family: "'Kaushan Script', cursive" },
    { id: "font-34", name: "Rock Salt", family: "'Rock Salt', cursive" },
    { id: "font-35", name: "Marker", family: "'Shadows Into Light', cursive" },
    { id: "font-36", name: "Quick Scribble", family: "'Reenie Beanie', cursive" },
    { id: "font-26", name: "La Belle", family: "'La Belle Aurore', cursive" },
    { id: "font-41", name: "Stalemate", family: "'Stalemate', cursive" },
    { id: "font-47", name: "Messy", family: "'Bad Script', cursive" },
    { id: "font-52", name: "Bilbo", family: "'Bilbo', cursive" },
    { id: "font-53", name: "Rainbow", family: "'Over the Rainbow', cursive" },
    { id: "font-54", name: "Marck", family: "'Marck Script', cursive" },
    { id: "font-56", name: "Give You Glory", family: "'Give You Glory', cursive" },
    { id: "font-60", name: "Merienda", family: "'Merienda', cursive" },
    { id: "font-63", name: "Mr Dafoe", family: "'Mr Dafoe', cursive" },
    { id: "font-65", name: "Mrs Sheppards", family: "'Mrs Sheppards', cursive" },
    { id: "font-66", name: "Nanum Pen", family: "'Nanum Pen Script', cursive" },
    { id: "font-67", name: "Neucha", family: "'Neucha', cursive" },
    { id: "font-70", name: "Sue Ellen", family: "'Sue Ellen Francisco', cursive" },
    { id: "font-73", name: "Walter", family: "'Walter Turncoat', cursive" },
    { id: "font-74", name: "Zeyada", family: "'Zeyada', cursive" },

    // Unique / Modern
    { id: "font-13", name: "WindSong", family: "'WindSong', cursive" },
    { id: "font-21", name: "Euphoria", family: "'Euphoria Script', cursive" },
    { id: "font-22", name: "Kristi", family: "'Kristi', cursive" },
    { id: "font-25", name: "Clicker", family: "'Clicker Script', cursive" },
    { id: "font-27", name: "Meddon", family: "'Meddon', cursive" },
    { id: "font-37", name: "League", family: "'League Script', cursive" },
    { id: "font-42", name: "Meie", family: "'Meie Script', cursive" },
    { id: "font-44", name: "Dr Sugiyama", family: "'Dr Sugiyama', cursive" },
    { id: "font-46", name: "Seaweed", family: "'Seaweed Script', cursive" },
    { id: "font-48", name: "Graffiti", family: "'Calligraffitti', cursive" },
    { id: "font-49", name: "Montez", family: "'Montez', cursive" },
    { id: "font-55", name: "Vibes", family: "'Vibes', cursive" },
    { id: "font-57", name: "Jim Nightshade", family: "'Jim Nightshade', cursive" },
    { id: "font-58", name: "Jules Love", family: "'Jules Love', cursive" },
    { id: "font-59", name: "Long Cang", family: "'Long Cang', cursive" },
    { id: "font-62", name: "Mr Bedfort", family: "'Mr Bedfort', cursive" },
    { id: "font-64", name: "My Soul", family: "'My Soul', cursive" },
    { id: "font-69", name: "Shadows Two", family: "'Shadows Into Light Two', cursive" },
    { id: "font-71", name: "Sunshiney", family: "'Sunshiney', cursive" },
    { id: "font-72", name: "Waiting", family: "'Waiting for the Sunrise', cursive" },
];
